spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog-system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 198b07dcb7379fd9
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 26739
      password: JPAdGNRrBGN6yHZ7
      database: 0
  ai:
    dashscope:
      api-key: sk-b7b3fb1052354fa59a34816df1e0306d
      chat:
        options:
          model: qwen-max

springdoc:
  api-docs:
    enabled: false

sa-token:
  jwt-secret-key: jwttwj

blog:
  upload:
    dir: /www/wwwroot/blog-system/blog-server/uploads
    public-url: http://47.88.48.16:8080
